// ========== 全局状态管理 ==========
export const state = {
    config: null,
    dom: null,
    bootstrapData: null,
    teams: [],
    sessions: [],
    activeSession: null,
    availableRoles: [],
    persons: [],
    roleTemplates: [],
    externalImportSources: [],
    selectedTeamId: null,
    selectedProfileId: null,
    teamDraftMode: false,
    teamDraftSelectedRoleIds: new Set(),
    teamFilterKeyword: '',
    profileFilterKeyword: '',
    selectedImageBase64: null,
    locale: 'zh-CN',
    persistentlyMutedRoleNames: new Set(),
    excludedRoleNamesForNextRound: new Set(),
    selectedIncludeRoleIds: new Set(),
    workspaceMode: 'team',
    roleSelectionExpanded: false,
    latestRoleDraft: null,
    latestRoleDraftMeta: null,
    selectedRoleStudioModel: '',
    selectedRoleRuntimeModel: '',
    roleStudioSources: null,
    selectedRoleStudioEngine: 'hybrid',
    selectedRoleStudioContextMode: 'none',
    selectedRoleStudioReferenceIds: new Set(),
    advancedRoleEditorExpanded: false,
    launcherSelectedPersonIds: new Set(),
    launcherRoleFilterKeyword: '',
    launcherRoleTagFilter: '',
    latestSelectionTrace: null,
    memoryReflection: null,
    memoryCandidates: [],
    memoryIndexRepair: {
        loading: false,
        scan: null,
        lastAction: null,
        error: ''
    }
};
